### ISSUE TITLE
first person issues

### ISSUE THREAD

**Issue by sirartorios** [glados1235/FemmployeeMod#1]
all items are a bit strange in first person, however its nothing gamebreaking, the only exception to that is the shotgun oh boi that ones a little too broken for use. other than that all my friends and I have been loving the mod keep up the spicy work~~~I'm not sure if it's in your capability of fixing but if it is me and my friends would def mark it mod of the year.

**Comment by glados1235** [comment]
hey hey! glad to hear it!
the strange item holding in first person is a bug with the Model Replacement API, it is known and they are trying to fix it.
it is not our end, best thing to do is wait and hope a fix comes soon.

thank you for using our mod though!

**Comment by sirartorios** [comment]
Roger if its not an issue with your mod ill close this as its not an "issue" on your end, cheers!
