### ISSUE TITLE
Compatibility with MoreCompany and other such stuff

### ISSUE THREAD

**Issue by Shaneilenin** [glados1235/FemmployeeMod#3]
Hello! Is it possible/any plans to tweak model to better work with MoreCompany cosmetics (and basically any other stuff that snaps to player model like things from TooManyEmotes)? Basically im about arm/head things, as they are seems shifted not for a much, and maybe some small tweaks to model proportions may fix it, while chest ones i suppose isnt those which can be easily or at all fixed here :D

Nice mod though, atm its best what i found for my wife, she much liked it :)

Also if it applicable some tweaks to thickness slider would be also appreciated, to be able to set somewhat lesser than current min- parameter, if applicable, idk if it should go do separate issue :D

**Comment by glados1235** [comment]
hello!
glad to hear ya like our mod!

The way the Model Replacement API creates the suit model in-game makes it hard to have everything lined up. The MoreCompany cosmetics are linked to the base game player skeleton, not the skeleton of the Femmployee model overtop of the invisible base model, so any difference in offset from 2 bones will create those types of issues.

this makes it hard to fix for the most part, but there are smaller ways that we can still tweak the mod setup to line things up _juuuust_ a little better, and that is planned.


In terms of minus sliders, they have been planned for a while. That falls onto TiltedHat, the creator of the used models. They have been very busy with IRL stuff, so they haven't had time to get around to working on those shape keys on the models, but they are planned to be included!

**Comment by Shaneilenin** [comment]
Nice to see this stuff are at least somewhat planned!

In recent games with our party we already happen to chat a bit about your mod again a couple times, and may say everyone of us agree your mod is the best among all ones whose tried to implement female player model xD and overall quality of it is really high :) nicely fits without really breaking vanilla vibes (if not do mindless x5-boob-model ofc -_-), and ability to tweak color and parts of model to your liking is very good at creating your own characters style (our current characters, me and wife :D https://imgur.com/a/AL9lmxJ)

We are curious now if you ever thought of plans to do something similar but for male character :) (as vanilla male-ployee now looks a bit ugly compared to femm-ployee quality xD), i think if you ever manage it will be just very nice universal full-replacement of vanilla suit!

and yeah i hope you dont mind i message to you all this through github issue xD

**Comment by glados1235** [comment]
mh yeah! there is a good reason the multiplier for others is client-side based on what YOURS is set too, people just wouldn't stop asking for it, but we didn't want something like that set up in a way that would bother others lol

also, the base model IS gender-neutral by default, just curvy.
its kinda hard right without more shape sliders to achieve a more standard male shape for sure, but the goal is everything under one model.

as a side note, the best way to reach out is through our thread on the "Lethal Company Modding" Discord server

if you join the server you should be able to find the thread [here](https://canary.discord.com/channels/1168655651455639582/1286906558361505893)!

**Comment by Shaneilenin** [comment]
yeah i scrolled your discord thread and now more aware about how things with this mod going :) i guess it may be nice to attach link or some mention to mod's page, as for us for ex its turned on unclear where to write if anything :D

And yeah surely i mean figure type rather than gender, will be nice at some point be able to tune model to way more male degree both in shapes and custom parts and tbh i will be quite surprised if you will at any point really manage to fit that in one model.

so i close issue then, thanks for answering!
